# Generated by Django 6.0.6 on 2026-07-20 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyntheticDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="synthetic/")),
                ("rows_generated", models.BigIntegerField()),
                ("quality_score", models.FloatField(default=0)),
                ("privacy_score", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="synthetic_datasets",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
